# Generated by Django 3.1.1 on 2020-09-26 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Type',
        ),
    ]
